application/main/controllers.py
from flask import Blueprint, request, render_template, flash, \
    g, session, redirect, url_for, jsonify, abort, url_for, make_response
from werkzeug.security import check_password_hash
from application.mod_auth.models import User
from application.mod_auth.controllers import get_user_object, get_fullname
from application.mod_module.forms import CreateModuleForm
from .forms import *
from application.mod_module.models import *
from application.mod_module.controllers import get_modules, get_quotes
from application import db, app, socketio
import flask_login

mod_main = Blueprint('mod_main', __name__, url_prefix='/',\
     template_folder='templates/')

@mod_main.route('/', methods=['GET'])
def index():

    if 'flask_login.mixins.AnonymousUserMixin' in str(flask_login.current_user):
        # Couldn't figure out a better way to do this
        return render_template('index.html')
    else:
        return redirect(url_for('mod_main.dashboard'))


@mod_main.route('/dashboard/', methods=['GET'])
@flask_login.login_required
def dashboard():
    create_form = CreateModuleForm()
    current_user=str(flask_login.current_user)
    mdoule_in_as_student, mdoule_in_as_tutor = get_number_of_module_in(current_user)
    
    return render_template(
        'dashboard/index.html',
        create_form=create_form,
        modules = get_modules(),
        mdoule_in_as_student = mdoule_in_as_student or 0,
        mdoule_in_as_tutor = mdoule_in_as_tutor or 0,
        current_user = str(flask_login.current_user),
        random_quote = get_quotes())


@mod_main.route('/profile/', methods=['GET'])
@flask_login.login_required
def profile():
    current_user=str(flask_login.current_user)
    mdoule_in_as_student, mdoule_in_as_tutor = get_number_of_module_in(current_user)
    info = User.query.filter_by(username=current_user).first()


    return render_template(
        'profile/index.html',
        current_user=current_user,
        mdoule_in_as_student = mdoule_in_as_student,
        mdoule_in_as_tutor = mdoule_in_as_tutor,
        email = info.email,
        joined_on = info.created_on.date(),
        profileForm = ProfileForm(),
        info = info)


@mod_main.route('/edit_profile/', methods=['POST'])
@flask_login.login_required
def edit_profile():
    form = ProfileForm(meta={'csrf_token' : True})
    if form.validate_on_submit():
        firstname = form.data.firstname
        lastname = form.data.lastname


    








@mod_main.route('/search_student/', methods=['GET'])
@flask_login.login_required
def search_student():
    student = request.args['student'].lower()
    u = User.query.all()
    if len(student.strip()) == 0:
        return jsonify(data=[])
    # TODO: Refactor this to use filter lambda function
    # to extract users that fit criteria
    s = []
    for i in u:
        if (student in i.username.lower()) or (student in i.email.lower()):
            s.append((i.username, 
            get_fullname(i.username),
            i.email))
    return jsonify(data=s)





def get_number_of_module_in(current_user):
    mdoule_in_as_student = 0
    mdoule_in_as_tutor = 0
    for i in ClassRoom.query.filter_by(member_username=current_user):
        m = Module.query.filter_by(module_id=i.module_id).first()
        if i.member_username == m.module_tutor_id:
            mdoule_in_as_tutor += 1
        else:
            mdoule_in_as_student += 1
    
    return mdoule_in_as_student, mdoule_in_as_tutor

application/mod_auth/controllers.py
from flask import Blueprint, request, render_template, flash, \
    g, session, redirect, url_for, jsonify, abort, url_for, make_response
from werkzeug.security import check_password_hash
from application.mod_auth.models import User
from application import db, app
import flask_login
from .forms import *

# Login manger setup
login_manager = flask_login.LoginManager()
login_manager.init_app(app)
@login_manager.user_loader
def load_user(username):
    return User.query.filter_by(username=username).first()


# Define the blueprint: 'auth', set its url prefix: app.url/auth
mod_auth = Blueprint('mod_auth', __name__, url_prefix='/auth',\
     template_folder='templates/')
login_manager.login_view = "mod_auth.index"
login_manager.login_message = "Please log in to access this page"


@mod_auth.route('/', methods=['GET'])
def index():
    form1 = SigninForm()
    form2 = SignupForm()
    return render_template(
        'auth/auth.html',
        form1=form1,
        form2=form2
    )



# Set the route and accepted methods
@mod_auth.route('/signup/', methods=['POST'])
def signup():
    '''
    Register a user onto the platform
    returns: flask.jsonify()
    '''
    
    form = SignupForm(meta={'csrf': False})

    if form.validate_on_submit():
        try:
            user = User(form.signup_username.data, form.signup_email.data, form.signup_password.data, \
                form.signup_firstname.data, form.signup_lastname.data)
            db.session.add(user)
            db.session.commit()
            flash("Account Created Successfully")
            return redirect(url_for('mod_main.dashboard'))
        except Exception:
            flash("Account Creation was Unsuccessfull")
    else:
        flash("Form submitted was invalid")
    
    return redirect(url_for('mod_auth.index'))



@mod_auth.route('/signin/', methods=['POST'])
def signin():
    '''
    Validate a username and password and 
    Sign the user in
    returns: flask.jsonify() || flask.render_template
    '''
    form = SigninForm(meta={'csrf_token':True})
    next,msg = None, ''

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.login_username.data).first()

        if (user is not None) and \
            (check_password_hash(user.password, form.login_password.data)):
            flask_login.login_user(user, remember=True)
            user.authenticated = True
            db.session.add(user)
            db.session.commit()
            msg = 'Logged in Successfully.'

            next = request.args.get('next')
            if not is_safe_url(next):
                return abort(400)
        
        else:
            msg = 'Username or Password was incorrect.'
        return redirect(next or url_for('mod_main.index'))

    else:
        msg = 'Form submitted was invalid'

    return jsonify(msg=msg)


@mod_auth.route('/signout/', methods=['GET'])
@flask_login.login_required
def signout():
    '''
    Sign a user out from the platform 
    returns: flask.render_template()
    '''
    user = User.query.filter_by(username=\
        flask_login.current_user.username).first()
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    flask_login.logout_user()
    flash('Successfully Logged Out.')
    
    return redirect(url_for('mod_main.index'))



def is_safe_url(target):
    '''
    Validates a redirection url to make sure 
    it is going to the same domain as the app
    params: target (str)
    '''
    from urllib.parse import urlparse, urljoin
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and \
           ref_url.netloc == test_url.netloc



def get_user_object(username):
    '''
    Returns a user object
    returns: User
    '''
    return User.query.filter_by(username=username).first()


@app.template_filter('fullname')
def get_fullname(username):
    u = User.query.filter_by(username=username).first()
    return f'{u.first_name} {u.last_name}'

application/mod_chat/controllers.py
from flask import Blueprint, request, render_template, flash, \
    g, session, redirect, url_for, jsonify, abort, url_for, make_response
from application import db, app
import flask_login
from .forms import *
from application.mod_auth.models import *
from application.mod_auth.controllers import *
from application.mod_chat.models import * 


mod_chat = Blueprint('mod_chat', __name__, url_prefix='/chat',\
     template_folder='templates/')



@mod_chat.route('/', methods=['GET'])
@flask_login.login_required
def index():
    return render_template(
        'chat/index.html',
        current_user = str(flask_login.current_user))




@mod_chat.route('/search_user/', methods=['GET'])
@flask_login.login_required
def search_user():
    user = request.args['user'].lower()
    u = User.query.all()
    if len(user.strip()) == 0:
        return jsonify(data=[])
    # TODO: Refactor this to use filter lambda function
    # to extract users that fit criteria
    s = []
    for i in u:
        if (user in i.username.lower()) or (user in i.email.lower()) or \
            (user in i.first_name.lower())  or (user in i.last_name.lower()) :
            s.append((i.username, 
            get_fullname(i.username),
            i.email))
    return jsonify(data=s)



@mod_chat.route('/get_messages/', methods=['GET'])
@flask_login.login_required
def get_messages():
    current_user = str(flask_login.current_user)
    room = request.args['room']
    chat_id = get_chat_id(room)
    messages = Message.query.filter_by(chat_id=chat_id)
    data = []
    for i in messages:
        stat = ''
        if i.username == current_user:
            stat = 'odd'
        data.append((i.username, stat, i.content, i.created_on))
    return jsonify(data = data)




@mod_chat.route('/get_all_messages/', methods=['GET'])
@flask_login.login_required
def get_all_messages():
    # Get all chat ids that has this current user
    # and also get the receiver
    chat_ids = []
    receiver = []
    current_user = str(flask_login.current_user)
    for i in Chat.query.all():
        if i.user1 == current_user:
            receiver.append(i.user2)
            chat_ids.append(i.chat_id)
        elif i.user2 == current_user:
            receiver.append(i.user1)
            chat_ids.append(i.chat_id)
    # Get all the last messages 
    last_messages = []
    for i in chat_ids:
        m = Message.query.filter_by(chat_id = i).all()
        last_messages.append(m[-1].content)
    
    data = []
    le = 0 

    for i in receiver:
        data.append((i, last_messages[le]))

    return jsonify(data = data)




def new_chat(room):
    users = room.split('-')
    # Check if that chat already exist
    c = Chat.query.filter_by(user1=users[0], user2=users[1]).first()
    if c is None:
        c = Chat(users[0], users[1])
        db.session.add(c)
        db.session.commit()
        return c.chat_id
    else:
        return c.chat_id

def get_chat_id(room):
    users = room.split('-')
    c = Chat.query.filter_by(user1=users[0], user2=users[1]).first()
    if c is not None:
        return c.chat_id
    else:
        raise Exception

def save_msg(chat_id, msg):
    m = Message(chat_id, str(flask_login.current_user), msg)
    db.session.add(m)
    db.session.commit()
    return True

application/mod_todo/controllers.py
from flask import Blueprint, request, render_template, flash, \
    g, session, redirect, url_for, jsonify, abort, url_for, make_response
from application import db, app
from werkzeug.security import check_password_hash
from application.mod_todo.models import Todo
from application.mod_auth.controllers import get_user_object
import flask_login

mod_todo = Blueprint('mod_todo', __name__, url_prefix='/todo',\
     template_folder='templates/')

@mod_todo.route('/', methods=['GET'])
@flask_login.login_required
def index():
    u = get_user_object(str(flask_login.current_user))
    todos = Todo.query.filter_by(owner_id=u.username)
    return render_template(
        'todo/index.html',
        todos=todos)



@mod_todo.route('/add/', methods=['GET'])
@flask_login.login_required
def add():
    data = request.args['data']
    u = get_user_object(str(flask_login.current_user))
    todo = Todo(u.username, data)
    db.session.add(todo)
    db.session.commit()
    return jsonify(
        data=True, 
        id=todo.todo_id)



@mod_todo.route('/crossoff/', methods=['GET'])
@flask_login.login_required
def crossoff():
    todo_id = request.args['todo_id']
    todo = Todo.query.filter_by(todo_id=todo_id).first()
    todo.status = 'checked'
    db.session.add(todo_id)
    db.session.commit()
    return jsonify(data=True)


@mod_todo.route('/remove/', methods=['GET'])
@flask_login.login_required
def remove():
    todo_id = request.args['todo_id']
    todo = Todo.query.filter_by(todo_id=todo_id).first()
    db.session.delete(todo)
    db.session.commit()
    return jsonify(data=True)

application/templates/dashboard/index.html
{% extends 'base.html' %}
{% block title %} Dashboard {% endblock %}
{% block content %}
{% include 'dashboard/nav.html' %}
{% include 'module/create_module.html' %}
{% include 'module/join_module.html' %}

<div class="container w3-round w3-card jumbotron w3-pale-green">
    <h3><u class="w3-text-teal">Modules</u></h3>
    <div class="w3-teal w3-right w3-row w3-card w3-round">
        <button class="w3-half w3-button" data-toggle="modal" data-target="#createModule">Create Module {{module_in_as_student}}</button>
        <button class="w3-half w3-button" data-toggle="modal" data-target="#joinModule">Join a Module</button>
    </div>
    <u><p class="text-muted w3-round w3-small w3-center">{{random_quote}}</p></u>
</div>

<div class="container w3-padding">
    <div class="input-group">
        <span class="input-group-addon nk-ic-st-pro"><i class="notika-icon notika-search w3-text-teal"></i></span>
        <div class="nk-int-st">
            <input type="text" class="form-control" id="search_module" name="search_module"
                placeholder="Search Module by Name">
        </div>
    </div>
</div>

<div class="notika-status-area">
    <div class="container">
        <div class="row" id="list_of_modules">
            {% for module in modules %}
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                <div class="wb-traffic-inner sm-res-mg-t-30 tb-res-mg-t-30 w3-round w3-card w3-pale-green">
                    <div class="w3-small">
                        <p>{{module.module_name | capitalize}}</p>
                        <p class="text-muted">Module Tutor: {{module.module_tutor_id|fullname}}</p>
                        <p class="text-muted">Module Code: {{module.module_code}}</p>
                        <p class="text-muted w3-tiny w3-text-teal">ID: {{module.module_id}}</p>
                        <a href="/module/view/{{module.module_id}}" class="w3-button w3-teal w3-round">View</a>
                    </div>
                </div>
                <hr>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

{% block js_content%}
<script>
    $("#join_module_search").on('keyup', function () {
        $('#search_module_list').empty();
        $.ajax({
            'data': { data: $('#join_module_search').val(), action: "get_mod" },
            'url': '/module/join_module/',
            'type': 'GET',
            'success': function (res) {
                for (var i = 0; i < res.data.length; i++) {
                    $('#search_module_list').append(
                        `<div class="w3-small wb-traffic-inner sm-res-mg-t-30 tb-res-mg-t-30 w3-round">
                            <div>
                                <p class="w3-small">Module Name: ${res.data[i][0]}</p>
                                <p class="w3-small">Module Tutor: ${res.data[i][2]}</p>
                                <p class="text-muted w3-small">Module ID: ${res.data[i][1]}</p>
                                <button id="${res.data[i][1]}" onclick="joinModule('${res.data[i][1]}')"
                                 class="w3-button w3-gray w3-round">Join</button>
                            </div>
                        </div> <br>`);

                }
            },
            'error': function (res) {
            }
        });
    });

    function joinModule(module_id) {
        $.ajax({
            'data': { module_id: module_id, action: 'join' },
            'url': '/module/join_module/',
            'type': 'GET',
            'success': function (res) {
                if (res.msg == "Success") {
                    $("#" + module_id).toggleClass('w3-gray w3-teal');
                    $("#" + module_id).html("Joined");
                } else {
                    $("#" + module_id).toggleClass('w3-gray w3-red');
                    $("#" + module_id).html("Error Occured");
                }
            }
        });
    }


    $("#search_module").on('keyup', function () {
        $.ajax({
            'data': { data: $('#search_module').val() },
            'url': '/module/search_my_module/',
            'type': 'GET',
            'success': function (res) {
                var temp = $('#list_of_modules').children();
                $('#list_of_modules').empty();
                for (var i = 0; i < res.data.length; i++) {
                    $('#list_of_modules').append(
                        `<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                        <div class="wb-traffic-inner sm-res-mg-t-30 tb-res-mg-t-30 w3-round">
                            <div class="w3-small">
                                <p>${res.data[i][0]}</p>
                                <p class="text-muted">Module Tutor: ${res.data[i][1]}</p>
                                <p class="text-muted">Module Code: ${res.data[i][2]}</p>
                                <p class="text-muted w3-tiny w3-text-teal">ID: ${res.data[i][3]}</p> 
                                <a href="/module/view/${res.data[i][3]}" class="w3-button w3-teal w3-round">View</a>
                            </div>
                        </div>
                        <hr></div>`
                    );

                }
            }
        });
    });

</script>

{% endblock %}

application/templates/dashboard/nav.html
<!-- Main Menu area start-->
<div class="main-menu-area mg-tb-40">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <ul class="nav nav-tabs notika-menu-wrap menu-it-icon-pro">
                    <li><a data-toggle="" href="{{url_for('mod_main.dashboard')}}">Home</a>
                    </li>
                    <li><a data-toggle="" href="{{url_for('mod_todo.index')}}">My ToDo</a>
                    </li>
                    <li><a data-toggle="" href="{{url_for('mod_notification.index')}}">Notification</a>
                    </li>
                    <li><a data-toggle="" href="{{url_for('mod_whiteboard.index')}}">White Board</a>
                    </li>
                    <li><a data-toggle="" href="{{url_for('mod_chat.index')}}">Chats</a>
                    </li>
                    <li><a data-toggle="" href="{{url_for('mod_main.profile')}}">Profile</a>
                    </li>
                    <li class="w3-right"><a data-toggle="" href="{{url_for('mod_auth.signout')}}"><u>Logout</u></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>